Desktop/project_ip/fmi-cazare/config/routes.rb
FmiCazare::Application.routes.draw do

  resources :rooms
  resources :guests
  resources :dorms_categories
  resources :dorms
  resources :documents
  resources :accomodations

  root to: 'guests#index'

  #omniauth
  get '/auth/:provider/callback', to: 'user_sessions#create'
  get '/auth/failure', to: 'user_sessions#failure'

  #logout
  get '/logout', to: 'user_sessions#destroy'

  #pagini student
  match '/creeaza_cerere', to: 'accomodations#new', via: 'get'
  match '/vezi_cerere', to: 'accomodations#show', via: 'get'
  match '/profil_student', to: 'accomodations#student_profile', via: 'get'
  match '/rezultate_verificare', to: 'accomodations#verified_results', via: 'get'
  match '/decizia_comisiei', to: 'accomodations#decision', via: 'get'
  match '/metodologie', to: 'accomodations#metodologie', via: 'get'
  match '/camine', to: 'accomodations#camine', via: 'get'
  match '/ajutor', to: 'guests#ajutor', via: 'get'

end

Desktop/project_ip/fmi-cazare/app/models/accomodation.rb
class Accomodation < ActiveRecord::Base
  has_many :documents, dependent: :destroy
  belongs_to :user
end

Desktop/project_ip/fmi-cazare/app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :accomodation
  before_destroy :delete_files, prepend: true

  private

  def delete_files
    File.delete(File.join('uploads', self.accomodation.user.uid.to_s, self.name)) if File.exist?(File.join('uploads', self.accomodation.user.uid.to_s, self.name))
  end
end

Desktop/project_ip/fmi-cazare/app/models/dorm.rb
class Dorm < ActiveRecord::Base
  has_many :rooms, dependent: :destroy
end

Desktop/project_ip/fmi-cazare/app/models/dorms_category.rb
class DormsCategory < ActiveRecord::Base
end

Desktop/project_ip/fmi-cazare/app/models/guest.rb
class Guest < ActiveRecord::Base
end

Desktop/project_ip/fmi-cazare/app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :dorm
  belongs_to :user
end

Desktop/project_ip/fmi-cazare/app/models/user.rb
class User < ActiveRecord::Base
  has_one :room
  has_one :accomodation
end

Desktop/project_ip/fmi-cazare/app/models/user_session.rb
class UserSession < ActiveRecord::Base
end

Desktop/project_ip/fmi-cazare/app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
end

Desktop/project_ip/fmi-cazare/app/controllers/dorms_controller.rb
class DormsController < ApplicationController
end

Desktop/project_ip/fmi-cazare/app/controllers/guests_controller.rb
class GuestsController < ApplicationController

  def index
    if get_current_user
      if get_current_user.is_student == "true"
        respond_to do |format|
          format.html { redirect_to '/creeaza_cerere' }
        end
      end
      if get_current_user.is_management == "true"
        respond_to do |format|
          format.html { redirect_to '/lista_cereri'}
        end
      end
      if get_current_user.is_admin == "true"
        respond_to do |format|
          format.html { redirect_to '/lista_cereri_admin'}
        end
      end
    else
      respond_to do |format|
        format.html # index.html.erb
      end
    end
  end

  def ajutor
    get_current_user
  end

end

Desktop/project_ip/fmi-cazare/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
end

Desktop/project_ip/fmi-cazare/app/helpers/accomodations_helper.rb
module AccomodationsHelper
end

Desktop/project_ip/fmi-cazare/app/helpers/application_helper.rb
module ApplicationHelper
end

Desktop/project_ip/fmi-cazare/app/helpers/documents_helper.rb
module DocumentsHelper
end

Desktop/project_ip/fmi-cazare/app/helpers/dorms_categories_helper.rb
module DormsCategoriesHelper
end

Desktop/project_ip/fmi-cazare/app/helpers/dorms_helper.rb
module DormsHelper
end

Desktop/project_ip/fmi-cazare/app/helpers/guests_helper.rb
module GuestsHelper
end

Desktop/project_ip/fmi-cazare/app/helpers/rooms_helper.rb
module RoomsHelper
end

Desktop/project_ip/fmi-cazare/app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

Desktop/project_ip/fmi-cazare/app/views/layouts/_header.html.erb
<div class = "navbar-header">
  <div class = "navbar navbar-default navbar-fixed-top navbar-static-top">
    <div class = "container">
      <%= link_to "FMI Cazare", root_path, class:"navbar-brand logo" %>

      <button class = "navbar-toggle" data-toggle = "collapse" data-target = ".navHeaderCollapse">
        <span class = "icon-bar"></span>
        <span class = "icon-bar"></span>
        <span class = "icon-bar"></span>
      </button>
      <div class = "collapse navbar-collapse navHeaderCollapse">
        <ul class = "nav navbar-nav navbar-right">
          <li><%= link_to "Metodologie", "http://www.unibuc.ro/n/student/Metodologie_si_reguli_de_cazare_prevederi_generale.php", target: "_blank"  %></li>
          <li><%= link_to "Prezentare Camine","http://www.unibuc.ro/n/student/Prezentarea_caminelor_Universitatii_din_Bucureti.php", target: "_blank" %> </li>
          <li><%= link_to "Ajutor","/ajutor/"%> </li>
          <% if !@current_user %>
            <li><%= link_to "Autentificare", "/auth/autentificare" %></li>
          <% else %>
            <% if @current_user.accomodation.nil? %>
                <li><a href="/creeaza_cerere">Cerere cazare</a></li>
            <% else %>
                <li><a href="/vezi_cerere">Vezi cererea</a>
            <% end %>
            <!--<li class="divider"></li>
            <li><a href="#">Vezi decizie comisie</a></li>-->
            <!--<li><a href="#">Notificari (0)</a></li>-->
            <li><a href="/logout">Deconectare</a></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

Desktop/project_ip/fmi-cazare/app/views/layouts/_headerOLD.html.erb
<header class = "navbar navbar-fixed-top navbar-inverse topmenu">
  <div class = "navbar-inner topmenu">
    <div class = "container-fluid topmenu">
      <%= link_to "FMI Cazare", root_path, class:"logo" %>
      <nav>
        <ul class = "nav navbar-nav navbar-right">
          <li><%= link_to 'Metodologie', '#' %></li>
          <li><%= link_to 'Prezentare camine', camine_path %></li>
          <% if !@current_user %>
            <li><a href="/auth/autentificare">Autentificare</a></li>
          <% else %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Cererea mea <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% if @current_user.accomodation.nil? %>
                  <li><a href="creeaza_cerere">Creeaza cerere</a></li>
                <% else %>
                  <li><a href="vezi_cerere">Vezi cerere</a>
                <% end %>
                <li class="divider"></li>
                <li><a href="#">Vezi decizie comisie</a></li>
              </ul>
            </li>
            <li><a href="#">Notificari (0)</a></li>
            <li><a href="/logout">Deconectare</a></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

Desktop/project_ip/fmi-cazare/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

Desktop/project_ip/fmi-cazare/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FmiCazare</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      		<%= yield %>
    </div>
  </body>
</html>